version: '3'

services:
  devops-toolkit:
    image: devops_toolkit
    ports:
      - "2231:22"
    volumes:
      - ./:/home/user/tf-module-security-groups
      - ./key:/home/user/key
      - ~/.aws:/root/.aws
    container_name: tf-module-security-groups_cn
    restart: unless-stopped
