name: release-please

on:
  workflow_run:
    workflows: ["pre-commit"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-as: "1.0.0"
          command: manifest
